### ISSUE TITLE
cant open python issue

### ISSUE THREAD

**Issue by AL280** [shahzain345/puppeteer-hcaptcha-solver#6]
HTTP Server started on http://myip:port
C:\Users\al\node_modules\puppeteer-hcaptcha-solver\lib\python\get_result.js:51
                            throw err;
                            ^

PythonShellError: python: can't open file 'C:\\Users\\al\\Downloads\\nocaptcha\\recognition\\_main.py': [Errno 2] No such file or directory

    at PythonShell.parseError (C:\Users\al\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\al\node_modules\python-shell\index.js:190:32)
    at ChildProcess.<anonymous> (C:\Users\al\node_modules\python-shell\index.js:182:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  executable: 'python',
  options: null,
  script: 'recognition\\_main.py',
  args: null,
  exitCode: 2
}

**Comment by shahzain345** [comment]
This is probably because the recognition folder was not downloaded on windows, I will fix this ASAP

**Comment by shahzain345** [comment]
Did the package install a recognition folder in your directory?

**Comment by AlbaDev1** [comment]
It created a recognition folder but there is nothing inside
