### ISSUE TITLE
div.task-image:nth-child(1)` failed: Waiting failed: 30000ms exceeded

### ISSUE THREAD

**Issue by inanbruneli** [shahzain345/puppeteer-hcaptcha-solver#9]
I'm trying to use the lib, but I'm facing the following error:

`
E:\Github\hcaptcha-python\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:59
                void this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                                    ^

TimeoutError: Waiting for selector `div.task-image:nth-child(1)` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (E:\Github\hcaptcha-python\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:59:37)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
`

I even tried changing the selector to: `div.task-image: nth-child(1)` - works with jquery
But, got: 

`
E:\Github\hcaptcha-python\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:59
                void this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                                    ^

TimeoutError: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (E:\Github\hcaptcha-python\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:59:37)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.16.1
`

**Comment by syahrul9088** [comment]
same
